modLoader = "javafml"
loaderVersion = "${neoforge_loader}"
license = "${license}"
issueTrackerURL="${issues_url}"

[[mods]]
modId = "${id}"
version = "${version}"
displayName = "${name}"
logoFile = "${id}.png"
logoBlur = false
authors = "${author}"
description = '''${description}'''

[[mixins]]
config = "${id}.mixins.json"

[[dependencies.${id}]]
modId = "neoforge"
type="required"
versionRange = "[${neoforge},)"
ordering = "NONE"
side = "BOTH"

[[dependencies.${id}]]
modId = "minecraft"
type="required"
versionRange = "${minecraft}"
ordering = "NONE"
side = "BOTH"
